### PR TITLE
Adding JSON unit test files

### LINKED ISSUE #43: Creation of unit tests
#### Definition of the test :

It would be great to automate the testing of the Psychometrics Toolkit by creating the unit tests.

### PR DESCRIPTION
**Pull request by kprusicka**
Closes #43

### CODE REVIEW

**Comment by kprusicka** [comment]
@BHoMBot check unit-tests

**Comment by kprusicka** [comment]
@BHoMBot Check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Review by FraserGreenroyd — APPROVED** [review]
This looks fine with the addition of some automated checks, nice work @kprusicka

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by kprusicka** [comment]
Thank you @BHoMBot

**Pull request merged**
