### PR TITLE
Unit tests updated

### LINKED ISSUE #59: An error occurred on a unit test
<samp>The following errors have been reported on unit tests in this repository.

**BHoM/Psychrometrics_Toolkit\.ci\Datasets\Compute\PartialVapourPressure.json**
Unit test set: PartialVapourPressure. Author: Karolina Prusicka
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: PartialVapourPressure(Double dryBulbTemperature).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Failed to run unit test. Errors given: 
		Failed to run with the given inputs

**BHoM/Psychrometrics_Toolkit\.ci\Datasets\Compute\TemperatureAtAltitude.json**
Unit test set: TemperatureAtAltitude. Author: Karolina Prusicka
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: TemperatureAtAltitude(Double altitude).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			08/09/2023 04:12:24
			Data returned for output 0 is different than expected.
			Expected value: 15, returned value from execution: 288.15.
</samp>

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #59 

unit tests for specified methods updated (used to be Celsius based, now Kelvin based).

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Review by FraserGreenroyd — APPROVED** [review]
Unit tests are passing, update is good, great work @Tom-Kingstone

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
