### PR TITLE
Combined methods with similar inputs

### LINKED ISSUE #12: Move methods from Climate Toolkit into Psychrometrics Toolkit
#### Description:
Add the following methods from Climate toolkit into Psychrometrics, following discussion on https://github.com/BuroHappoldEngineering/Climate_Toolkit/issues/204

- [x] DensityWater
- [x] SpecificHeatCapacityWater
- [x] SaturatedVapourPressureWater

Either replace with code previously in climate toolkit or with respective Psychrolib methods. 

Ensure documentation and QA/QC is complete and up-to-date for the methods.

### LINKED ISSUE #52: Combine compute methods to make computing certain values more user-friendly
#### Description:
Methods like DensityHumidityRatio, DensityRelativeHumidity and DensityWetBulbTemperature can be combined into a single method called Density, that has functionality to compute density from some given values. The Density method would take in these values and decide which calculation to do, then do the calculation and return the correct value. In the case where there is not enough information to compute, it will throw an error that accurately describes what is missing. If the user inputs more information and multiple methods can be used, it will select a method to use, and also output a message to the user that describes the inputs used to make the calculation.

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR
Closes #52 
Closes #12 

Three methods have been created: FromHumidityRatio, FromRelativeHumidity and FromWetBulbTemperature.
These methods take in dryBulbTemperature and pressure (with a default to air pressure at sea level), as well as a third input of: humidityRatio, relativeHumidity or wetBulbTemperature.
They then output density, enthalpy, dew-point temperature, humidity ratio, relative humidity, specific volume and wet-bulb temperature. These methods each replace 6 previous methods (18 in total) in functionality, as well as improving user experience searching for methods from the psychrometrics toolkit.

Additionally, moved methods DensityWater, SaturatedVapourPressureWater and SpecificHeatCapacityWater into Psychrometrics  Toolkit. (as per issue #12)

### Test files
[Psychrometrics_Toolkit.zip](https://github.com/BHoM/Psychrometrics_Toolkit/files/12511490/Psychrometrics_Toolkit.zip)
(the new methods are on the top right of the script, and use the same values to test as the old methods)

### Additional comments

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core

**Comment by Tom-Kingstone** [comment]
@BHoMBot check code-compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Changes make sense following call and walk through with @Tom-Kingstone and @jamesramsden-bh - happy to deploy

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
